fork = false
frame = "none"
idle = true
maximized = false
neovim-bin = "/usr/local/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["FantasqueSansM Nerd Font Propo"] # Will use the bundled Fira Code Nerd Font by default
size = 17.5

